export const GET_CART_API = "GET_CART_API" ;
export const DELETE_CART_API = "DELETE_CART_API" ;
export const UPDATE_CART_API = "UPDATE_CART_API" ;
export const GET_WISHLIST_API = "GET_WISHLIST_API" ;
export const DELETE_WISHLIST_API = "DELETE_WISHLIST_API" ;